
var sd_impactesamenaces = [{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2010,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2013,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2014,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2015,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"1. Canvi climàtic","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2009,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2010,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2011,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2012,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2013,"VALOR":18},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2014,"VALOR":35},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2015,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"10. Competència","DATA":2016,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2010,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2011,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2013,"VALOR":6},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2014,"VALOR":6},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2015,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"11. Predació","DATA":2016,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2010,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2013,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2014,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2015,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"12. Parasitisme","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2010,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2013,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2014,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2015,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"14. Hibridació","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2009,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2010,"VALOR":5},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2011,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2012,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2013,"VALOR":10},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2014,"VALOR":11},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2015,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2016,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2010,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2011,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2013,"VALOR":8},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2014,"VALOR":8},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2015,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2010,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2012,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2013,"VALOR":6},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2014,"VALOR":10},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2015,"VALOR":7},
{"GRUP":"Impactes","PARAMETRE":"17. Freqüentació","DATA":2016,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2010,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2013,"VALOR":7},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2014,"VALOR":6},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2015,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"18. Altres","DATA":2016,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2009,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2010,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2011,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2012,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2013,"VALOR":6},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2014,"VALOR":15},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2015,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2010,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2013,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2014,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2015,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"4. Alteració del medi hídric","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2009,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2010,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2011,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2012,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2013,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2014,"VALOR":7},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2015,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2016,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2010,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2013,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2014,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2015,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"6. Pol·lució","DATA":2016,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2009,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2010,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2011,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2012,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2013,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2014,"VALOR":9},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2015,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2010,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2012,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2013,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2014,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2015,"VALOR":1},
{"GRUP":"Impactes","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2016,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2009,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2010,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2011,"VALOR":0},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2012,"VALOR":2},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2013,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2014,"VALOR":4},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2015,"VALOR":3},
{"GRUP":"Impactes","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2002,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2010,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2012,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2013,"VALOR":6},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2014,"VALOR":4},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2015,"VALOR":5},
{"GRUP":"Amenaces","PARAMETRE":"1. Canvi climàtic","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2010,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2011,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2013,"VALOR":18},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2014,"VALOR":27},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2015,"VALOR":6},
{"GRUP":"Amenaces","PARAMETRE":"10. Competència","DATA":2016,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2002,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2010,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2011,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2013,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2014,"VALOR":4},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2015,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"11. Predació","DATA":2016,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2010,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2013,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2014,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2015,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"12. Parasitisme","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2010,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2013,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2014,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2015,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"14. Hibridació","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2010,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2011,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2013,"VALOR":10},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2014,"VALOR":11},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2015,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"15. Població o superfície recoberta petita","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2010,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2011,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2013,"VALOR":8},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2014,"VALOR":7},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2015,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"16. Aïllament biogeogràfic","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2010,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2011,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2013,"VALOR":10},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2014,"VALOR":7},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2015,"VALOR":8},
{"GRUP":"Amenaces","PARAMETRE":"17. Freqüentació","DATA":2016,"VALOR":3},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2010,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2013,"VALOR":5},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2014,"VALOR":7},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2015,"VALOR":6},
{"GRUP":"Amenaces","PARAMETRE":"18. Altres","DATA":2016,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2010,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2011,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2013,"VALOR":11},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2014,"VALOR":12},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2015,"VALOR":3},
{"GRUP":"Amenaces","PARAMETRE":"2. Reducció de l’hàbitat","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2002,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2010,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2013,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2014,"VALOR":6},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2015,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"3. Incendis forestals","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2010,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2013,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2014,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2015,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"4. Alteració del medi hídric","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2002,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2010,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2012,"VALOR":3},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2013,"VALOR":4},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2014,"VALOR":7},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2015,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"5. Pràctiques forestals inadequades","DATA":2016,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2010,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2013,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2014,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2015,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"6. Pol·lució","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2010,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2012,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2013,"VALOR":3},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2014,"VALOR":8},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2015,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"7. Canvis en el medi com a resultat de l’abandonament de pràctiques agroramaderes","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2002,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2010,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2013,"VALOR":3},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2014,"VALOR":3},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2015,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"8. Canvis en el medi com a resultat de la intensificació de pràctiques agroramaderes","DATA":2016,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2002,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2010,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2011,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2012,"VALOR":0},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2013,"VALOR":1},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2014,"VALOR":2},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2015,"VALOR":3},
{"GRUP":"Amenaces","PARAMETRE":"9. Altres alteracions de l’hàbitat","DATA":2016,"VALOR":1}]