
var sd_tesaurus = [{"ESPECIE":"Adoxa moschatellina","CATEGORIA":"EICP1","CFAC":"0"},
{"ESPECIE":"Aira praecox","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Allium pyrenaicum","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Arenaria fontqueri ssp. cavanillesiana","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Arisarum simorrhinum","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Asplenium (Phyllitis) sagittatum","CATEGORIA":"EICP1","CFAC":"E"},
{"ESPECIE":"Botrychium matricariifolium","CATEGORIA":"EICP1","CFAC":"E"},
{"ESPECIE":"Cheilanthes tinaei","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Cicendia filiformis","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Convolvulus siculus","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Cosentinia vellea","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Cypripedium calceolus","CATEGORIA":"EICP2","CFAC":"E"},
{"ESPECIE":"Dactylorhiza insularis","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Delphinium bolosii","CATEGORIA":"EICP1","CFAC":"E"},
{"ESPECIE":"Epipogium aphyllum","CATEGORIA":"EICP1","CFAC":"E"},
{"ESPECIE":"Erica cinerea","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Galium scabrum","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Geranium lanuginosum","CATEGORIA":"EICP1","CFAC":"V"},
{"ESPECIE":"Halimium halimifolium","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Hippuris vulgaris","CATEGORIA":"EICP1","CFAC":"E"},
{"ESPECIE":"Hypericum pulchrum","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Isoetes durieui","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Lavatera olbia","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Limonium girardianum","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Lotus parviflorus","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Melampyrum catalaunicum","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Myricaria germanica","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Potamogeton lucens","CATEGORIA":"EICP1","CFAC":"V"},
{"ESPECIE":"Potamogeton natans","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Potentilla montana","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Prunus lusitanica","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Salvia sylvestris ssp. valentina","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Saxifraga callosa ssp. catalaunica","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Saxifraga genesiana","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Saxifraga vayredana","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Silene mutabilis","CATEGORIA":"EICP1","CFAC":"0"},
{"ESPECIE":"Silene viridiflora","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Spiraea crenata ssp. parvifolia","CATEGORIA":"EICP1","CFAC":"E"},
{"ESPECIE":"Spiranthes aestivalis","CATEGORIA":"EIC","CFAC":"V"},
{"ESPECIE":"Succowia balearica","CATEGORIA":"EICP2","CFAC":"V"},
{"ESPECIE":"Trifolium diffusum","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Trifolium micranthum","CATEGORIA":"EIC","CFAC":"0"},
{"ESPECIE":"Viola bubanii","CATEGORIA":"EIC","CFAC":"0"}]