type lodash.js > sefa.js
type d3pie.min.js >> sefa.js
type async-min.js >> sefa.js
type regression.js >> sefa.js
type data_tesaurus.js >> sefa.js
type data_tendenciapobl.js >> sefa.js
type data_localitatscensadesany.js >> sefa.js
type data_impactesamenaces.js >> sefa.js
type data.js >> sefa.js
type fishnet.js >> sefa.js
type manage_sd.js >> sefa.js
type create_page.js >> sefa.js
type sefa_tables.js >> sefa.js
type colorbrewer.js >> sefa.js
type graphcolor.js >> sefa.js
type graphdata.js >> sefa.js
type graph_sefa.js >> sefa.js
type layer.js >> sefa.js
type mapa_layers_sefa.js >> sefa.js
type mapa_layers_diba.js >> sefa.js
type mapa_layers_icc.js >> sefa.js
type mapa_sefa.js >> sefa.js
type translate.js >> sefa.js
type sefa_config.js >> sefa.js
type main_.js >> sefa.js

